### ISSUE TITLE
Function Not Send?

### ISSUE THREAD

**Issue by zicklag** [dcchut/async-recursion#1]
Hey there, I wanted to use this in my project, but I'm getting an error that I don't get when manually adjusting the function for recursion:

```

error[E0277]: `(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)` cannot be sent between threads safely
  --> src/subsystems/crawler.rs:64:50
   |
64 |                     let aid = ctx.system.spawn().with(
   |                                                  ^^^^ `(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Send` for `std::ptr::Unique<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>`
   = note: required because it appears within the type `std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>>`
   = note: required because of the requirements on the impl of `axiom::actors::Processor<subsystems::crawler::IndexCrawler<P>, std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>>>` for `fn(subsystems::crawler::IndexCrawler<P>, axiom::actors::Context, axiom::message::Message) -> std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<(subsystems::crawler::IndexCrawler<P>, axiom::actors::Status), std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>>> + 'static)>> {subsystems::crawler::IndexCrawler::<P>::index_crawler}`
```

I noticed a TODO in the code about a `Send` option that is missing, is that related? Would it be simple enough to explain what must happen so I could make a PR?

**Comment by dcchut** [comment]
Yeah - it is related!  At the moment the macro converts an async function `async fn whatever() -> T` to a function returning `Pin<Box<dyn Future<Output = T>>` (i.e. there is no Send bound, which may be the cause of your issue).  

I think in general we would want to default to having a Send bound, but with the option to omit it, if necessary (e.g. if you used the macro as `#[async_recursion(?Send)]`.  To do this would require:

1. Modify [this function](https://github.com/dcchut/async-recursion/blob/5c93841323ef8418e48482400393f1e09d055f1f/src/lib.rs#L72) to pick up the `?Send` argument (if present).
2. Modify `expand` and `transform_sig` in [expand.rs](https://github.com/dcchut/async-recursion/blob/master/src/expand.rs) to accept a boolean (`has_send`?) indicating whether the Send bound is required or not.
3. Finally, near the bottom of `transform_sig` (where the TODO is), do something like:
`
let send_marker = if has_send {
        quote!(::core::marker::Send)
    } else {
        quote!()
    };
`
and then include `#send_marker` somewhere in bounds on the final line of that function.

**Comment by zicklag** [comment]
Yeah, I just check out the [`BoxFuture`](https://docs.rs/futures/0.3.4/futures/future/type.BoxFuture.html) that I used to workaround manually and I can see that it has the send bound, which explains why it worked the macro didn't. I think that defaulting to send is definitely reasonable. I'll try work in the changes you mentioned.

**Comment by zicklag** [comment]
OK, I've got it working! PR incoming. Is the note in the README about not considering lifetimes still relevant? I could remove that if it isn't.

**Comment by dcchut** [comment]
> OK, I've got it working! PR incoming. Is the note in the README about not considering lifetimes still relevant? I could remove that if it isn't.

Ah it isn't - I hacked together something which appears to work (but I never published the change to crates.io)
