### ISSUE TITLE
Recursive async fns made with the macro are lacking `#[must_use]`

### ISSUE THREAD

**Issue by rand0m-cloud** [dcchut/async-recursion#25]
Here is a [playground link](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=1b61b8b5901d1bdfdbfbc3183d1958f9) for demonstration, the function only executes once instead of the expected 10 times. The issue in the example is the missing `await` on the recursive call. 

Functions that are manipulated by this macro lose their `#[must_use]` warning that usually comes with `async`s. Manually adding the `#[must_use]` to `run` highlights the issue. Without the `#[must_use]`, it is very easy for programmers to forget the `await` and creates a confusing debugging experience with their code paths not executing.

**Comment by dcchut** [comment]
Thanks for the report!  Published in 1.0.2.
