### ISSUE TITLE
It breaks when there is another "Box"

### ISSUE THREAD

**Issue by Magicloud** [dcchut/async-recursion#33]
For example, this expanded line of return type. I have a `Box` type defined in the crate. Not sure if that is the reason the `Box` here is not qualified.

`::core::pin::Pin<Box<dyn ::core::future::Future<Output = Result<()>>>>`.

**Comment by dcchut** [comment]
This is intentional to allow support for both `std` and `no_std` use cases, see e.g. https://github.com/dcchut/async-recursion/issues/4#issuecomment-1262008880.
