### ISSUE TITLE
Add `'async_recursion` lifetime to generics

### ISSUE THREAD

**Issue by Sythanis** [dcchut/async-recursion#5]
While using the `async_recursion` proc_macro the lifetime must be set for any generics. It would be nice if proc_macro could add the lifetime to all generics, so that IDE's don't complain about `in-band` lifetimes. 

Now I need to do
```
#[async_recursion::async_recursion]
fn foo<S: SomeTrait + Send + 'async_recursion>(trait: S) -> u64 {
...
}
```
Goal would be 
```
#[async_recursion::async_recursion]
fn foo<S: SomeTrait + Send>(trait: S) -> u64 {
...
}
```

@dcchut I can try adding that.

**Comment by dcchut** [comment]
Ah good catch - I've put up a small [PR](https://github.com/dcchut/async-recursion/pull/6) which adds the `'async_recursion` bound to each generic parameter, but I need to convince myself (or be convinced!) that adding this bound to <every> generic parameter doesn't somehow break anything that was working before.

For example: the `contains_value` function in `src/test.rs` picks up an additional `T: 'async_recursion` bound which wasn't explicitly there before. (But maybe that's fine?)

**Comment by dcchut** [comment]
Actually maybe that example is fine - we have a reference `&'life0 T` with the bound `'life0 : 'async_recursion`, which (I think) implies that `T : 'async_recursion` (since our reference to `T` must outlive every reference in `T`)

**Comment by Sythanis** [comment]
@dcchut I have checked the test you have mentioned... To me it looks good, but I am by far good in lifetimes. 

If I understand lifetimes correctly any reference of genertic T must indeed outlive the scope of `'async_recursion`. If not we could have a `BoxFuture` somewhere that would use `T` after it has been de-allocated. 

I think adding the lifetime should be safe.

**Comment by dcchut** [comment]
Yeah, I agree.  Thanks for opening this issue 👍
